### ISSUE TITLE
简体字著名被翻译成了着名

### ISSUE THREAD

**Issue by Pehfan** [DoctorLai/Simplified-and-Traditional-Chinese#4]
![image](https://user-images.githubusercontent.com/22440412/131302366-262074ba-0635-4f0e-93c5-7edb310626fb.png)

![image](https://user-images.githubusercontent.com/22440412/131302207-72dc3742-01c6-4663-b64b-257735c908d0.png)

**Comment by DoctorLai** [comment]
感谢，这个问题比较麻烦，因为这个插件比较笨，就是按字转换的，如果本身是简体中文了，再转成简体中文，就有可能会出现这种情况。

**Comment by doctorlai-msrc** [comment]
您好，感谢。在最新版本 v1.1 中已经修复（Pending Google's Review）
