### ISSUE TITLE
Upgrading to Google Chrome V3 Manifest

### ISSUE THREAD

**Issue by DASmallWorlds** [DoctorLai/Simplified-and-Traditional-Chinese#7]
Title says it pretty much. I managed to do it on a [modified version of the plugin](https://github.com/DASmallWorlds/japanese-convert-tool-manifest-v3) but I'm not sure if it's complete that way. See my email for more details :-)

**Comment by DoctorLai** [comment]
https://github.com/DoctorLai/Simplified-and-Traditional-Chinese/pull/8
