### ISSUE TITLE
上一次更新新增黑名單後默認數值是undefined並引發錯誤而沒有運行翻譯

### ISSUE THREAD

**Issue by ronniechoyy** [DoctorLai/Simplified-and-Traditional-Chinese#9]
![image](https://github.com/DoctorLai/Simplified-and-Traditional-Chinese/assets/61714797/aab7fd35-af06-4ffd-b541-2bdf23f64be9)
![image](https://github.com/DoctorLai/Simplified-and-Traditional-Chinese/assets/61714797/873c46b4-5d0d-4732-8b67-2067e3b8039a)

感覺應該是默認值出了問題🤔
在別的瀏覽器重新下載默認數值也是undefined並觸發錯誤

**Comment by DoctorLai** [comment]
好的，这周末我改一下， 你可以 先把那个 undefined删除了 这样就能用。

**Comment by ronniechoyy** [comment]
好哦感謝～插件好用😉

**Comment by DoctorLai** [comment]
https://github.com/DoctorLai/Simplified-and-Traditional-Chinese/pull/10
已经提交到Chrome 在审核中，非常感谢。
